# Generated by Django 5.2.7 on 2025-11-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_remove_ingreso_cuenta_remove_ingreso_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='concepto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
