# Generated by Django 5.2.7 on 2025-11-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_movimiento_concepto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='alcaldia',
            field=models.CharField(blank=True, choices=[('ALVARO_OBREGON', 'Alvaro Obregon'), ('AZCAPOTZALCO', 'Azcapotzalco'), ('BENITO_JUAREZ', 'Benito Juárez'), ('COYOACAN', 'Coyoacan'), ('CUAJIMALPA', 'Cuajimalpa de Morelos'), ('CUAUHTEMOC', 'Cuauhtémoc'), ('GUSTAVO_A_MADERO', 'Gustavo A. Madero '), ('IZTACALCO', 'Iztacalco'), ('IZTAPALAPA', 'Iztapalapa'), ('LA_MAGDALENA_CONTRERAS', 'La Magdalena Contreras'), ('MIGUEL_HIDALGO', 'Miguel Hidalgo'), ('MILPA_ALTA', 'Milpa Alta'), ('TLAHUAC', 'Tlahuac'), ('TLALPAN', 'Tlalpan'), ('VENUSTIANO_CARRANZA', 'Venustiano Carranza'), ('XOCHIMILCO', 'Xochimilco'), ('OTRO', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='edad',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado'), ('DIVORCIADO', 'Divorciado'), ('VIUDO', 'Viudo'), ('UNION_LIBRE', 'Union libre'), ('OTRO', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('NO_BINARIO', 'No binario'), ('NO_ESPECIFICAR', 'Prefiero no especificar'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estadoactual',
            name='ocupacion_actual',
            field=models.CharField(blank=True, choices=[('ESTUDIANDO', 'Estudiando'), ('TRABAJANDO', 'Trabajando'), ('AMBOS', 'Estudiando y Trabajando'), ('EMPRENDIENDO', 'Emprendiendo'), ('BUSCANDO_TRABAJO', 'Buscando Trabajo'), ('OTRO', 'Otro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='estadoactual',
            name='sem_posible_abandono',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1),
        ),
        migrations.AlterField(
            model_name='estadoactual',
            name='ultimo_sem_cursado',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1),
        ),
        migrations.AlterField(
            model_name='factoresdesercion',
            name='costos',
            field=models.TextField(choices=[('MUY_IMPORTANTE', 'Muy importante'), ('IMPORTANTE', 'Importante'), ('INTERMEDIO', 'Intermedio'), ('POCO_IMPORTANTE', 'Poco importante'), ('NO_IMPORTANTE', 'No importante')]),
        ),
        migrations.AlterField(
            model_name='factoresdesercion',
            name='falta_apoyo',
            field=models.TextField(choices=[('MUY_IMPORTANTE', 'Muy importante'), ('IMPORTANTE', 'Importante'), ('INTERMEDIO', 'Intermedio'), ('POCO_IMPORTANTE', 'Poco importante'), ('NO_IMPORTANTE', 'No importante')]),
        ),
        migrations.AlterField(
            model_name='factoresdesercion',
            name='financieros',
            field=models.TextField(choices=[('MUY_IMPORTANTE', 'Muy importante'), ('IMPORTANTE', 'Importante'), ('INTERMEDIO', 'Intermedio'), ('POCO_IMPORTANTE', 'Poco importante'), ('NO_IMPORTANTE', 'No importante')]),
        ),
        migrations.AlterField(
            model_name='factoresdesercion',
            name='personales',
            field=models.TextField(choices=[('MUY_IMPORTANTE', 'Muy importante'), ('IMPORTANTE', 'Importante'), ('INTERMEDIO', 'Intermedio'), ('POCO_IMPORTANTE', 'Poco importante'), ('NO_IMPORTANTE', 'No importante')]),
        ),
        migrations.AlterField(
            model_name='factoresdesercion',
            name='rendimiento',
            field=models.TextField(choices=[('MUY_IMPORTANTE', 'Muy importante'), ('IMPORTANTE', 'Importante'), ('INTERMEDIO', 'Intermedio'), ('POCO_IMPORTANTE', 'Poco importante'), ('NO_IMPORTANTE', 'No importante')]),
        ),
        migrations.AlterField(
            model_name='factoresdesercion',
            name='salud_mental',
            field=models.TextField(choices=[('MUY_IMPORTANTE', 'Muy importante'), ('IMPORTANTE', 'Importante'), ('INTERMEDIO', 'Intermedio'), ('POCO_IMPORTANTE', 'Poco importante'), ('NO_IMPORTANTE', 'No importante')]),
        ),
    ]
